name: Get Certificate
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Retrieve certificate
      uses: sigstore/gh-action-sigstore-python@v2.1.1
      with:
        certificate: fulcio-certificate.crt

    - name: Show files 
      run: ls -lisa
